apiVersion: v1
kind: Pod
metadata:
  name: seonghun-debug
spec:
  volumes:
    - name: seonghun-volume
      persistentVolumeClaim:
        claimName: seonghun-fast-vol
  containers:
    - name: qem-container
      image: seonghunn/libigl
      command: ['/bin/sh', '-c', 'tail -f /dev/null']
      volumeMounts:
        - mountPath: '/qem/model/output'
          name: seonghun-volume
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 1
          memory: 1Gi
  restartPolicy: Never
