apiVersion: v1
kind: Pod
metadata:
  name: seonghun-test
spec:
  volumes:
    - name: seonghun-volume
      persistentVolumeClaim:
        claimName: seonghun-fast-vol
  containers:
    - name: qem-container
      image: seonghunn/libigl:latest
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: ["/usr/sbin/sshd -D & cd build && ./QEM bunny.obj bunny_out_0.01_kub 0.01"]
      ports:
        - containerPort: 22
      volumeMounts:
        - mountPath: '/qem/model/output'
          name: seonghun-volume
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 1
          memory: 1Gi
  restartPolicy: Never
