apiVersion: batch/v1
kind: Job
metadata:
  name: seonghun-test
spec:
  template:
    spec:
      volumes:
        - name: seonghun-volume
          persistentVolumeClaim:
            claimName: seonghun-fast-vol
      containers:
        - name: qem-container
          image: seonghunn/libigl:intcheck
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args: ['cd build && ./QEM bunny.obj bunny_out_0.01_kub 0.01']
          volumeMounts:
            - mountPath: '/qem/model/output'
              name: seonghun-volume
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
      restartPolicy: Never
  backoffLimit: 4
