apiVersion: apps/v1
kind: Deployment
metadata:
  name: seoh-ssh
  labels:
    k8s-app: http-example
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: http-example
  template:
    metadata:
      labels:
        k8s-app: http-example
    spec:
      containers:
        - image: linghao097/http_py39:latest
          name: http-server
          command:
            - /bin/zsh
            - -c
            - |
              mkdir -p /var/run/sshd
              /usr/sbin/sshd -D
          ports:
            - containerPort: 2000
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: seoh-fast-vol
              mountPath: /seoh_fast_cephfs
            - name: seoh-slow-vol
              mountPath: /seoh_slow_cephfs
      volumes:
        - name: seoh-fast-vol
          persistentVolumeClaim:
            claimName: seoh-fast-vol
        - name: seoh-slow-vol
          persistentVolumeClaim:
            claimName: seoh-slow-vol
